package net.dovale.entities;

import javax.persistence.Entity;

@Entity
public class Teacher extends EntityAutoGeneratedID {

    private String name;
    private String pictureURL;
    private String email;

}
